main="drybox_test"

[drybox]
target_humidity = 10
target_temperature = 40

unsafe_temperature = 80
version = "1.0a"

[drybox.hardware]
#heater and fans are controlled by a bank of relays
heater_pin = 10
recirculation_fan_pin = 11
exhaust_fan_pin = 12

# hygrometer pin is running on a "1-wire" DHT communication protocol
hygrometer_pin = 28

# Pico has a 
led_pin = "LED"
thermister_pin = 4

[drybox.controls]
timeout_s = 600
sample_rate = 0.75

heater_hysteresis = 1

recirculation_cycle_period_s = 0.10
recirculation_cycle_percent = 10
exhaust_duration_s = 15

sensor_initial_wait_ms = 2000
sensor_settle_duration_s = 15

measurement_interval_s = 10
total_measurement_duration_s = 90
slope_threshold = 0.25
